exclude: uv.lock
repos:
- repo: https://github.com/crate-ci/typos
  rev: v1.47.2
  hooks:
    - id: typos
- repo: https://github.com/tombi-toml/tombi-pre-commit
  rev: v1.1.2
  hooks:
    - id: tombi-format
    - id: tombi-lint
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.17
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
